"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommentsBoard = exports.CommentsWrapper = exports.Details = exports.Goto = exports.Search = exports.TableBoard = exports.RichEditor = exports.SayHello = void 0;
var SayHello_1 = require("./components/SayHello");
Object.defineProperty(exports, "SayHello", { enumerable: true, get: function () { return __importDefault(SayHello_1).default; } });
var RichEditor_1 = require("./components/RichEditor");
Object.defineProperty(exports, "RichEditor", { enumerable: true, get: function () { return __importDefault(RichEditor_1).default; } });
var TableBoard_1 = require("./components/TableBoard");
Object.defineProperty(exports, "TableBoard", { enumerable: true, get: function () { return __importDefault(TableBoard_1).default; } });
var Search_1 = require("./components/Search");
Object.defineProperty(exports, "Search", { enumerable: true, get: function () { return __importDefault(Search_1).default; } });
var Goto_1 = require("./components/Goto");
Object.defineProperty(exports, "Goto", { enumerable: true, get: function () { return __importDefault(Goto_1).default; } });
var Details_1 = require("./components/Details");
Object.defineProperty(exports, "Details", { enumerable: true, get: function () { return __importDefault(Details_1).default; } });
var CommentsWrapper_1 = require("./components/CommentsWrapper");
Object.defineProperty(exports, "CommentsWrapper", { enumerable: true, get: function () { return __importDefault(CommentsWrapper_1).default; } });
var CommentsBoard_1 = require("./components/CommentsBoard");
Object.defineProperty(exports, "CommentsBoard", { enumerable: true, get: function () { return __importDefault(CommentsBoard_1).default; } });
